perl qutdownload-bld.pl >index-001.list
perl qutdownload-bus.pl >index-002.list
perl qutdownload-crt.pl >index-003.list
perl qutdownload-edu.pl >index-004.list
perl qutdownload-eng.pl >index-005.list
perl qutdownload-hth.pl >index-006.list
perl qutdownload-itn.pl >index-007.list
perl qutdownload-law.pl >index-008.list
perl qutdownload-sci.pl >index-009.list
